sp:
  user-service:
    users: "[]"

spring:
  application:
    name: user-service
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka1:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
rabbitmq:
    host: 176.135.28.27
    port: 5672
    username: admin
    password: admin
